
spring.datasource.url=jdbc:postgresql://localhost:5432/cats
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

validation.owner.name=50
validation.cat.name=50
validation.cat.breed=50

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest